// plugin/src/ui/components/FileHistoryModal.svelte
<script lang="ts">
  import type { FileVersionItem } from "../../types";
  import type { HistoryState } from "../file-history-types";

  export let currentVersion: number;
  export let state: HistoryState;
  export let restoringVersion: number | null;
  export let onRestore: (version: number) => void;

  function formatTimestamp(value: string): string {
    const parsed = new Date(value);
    if (Number.isNaN(parsed.getTime())) {
      return value;
    }

    return parsed.toLocaleString();
  }

  function buildVersionDescription(version: FileVersionItem): string {
    const parts = [
      version.created_at ? formatTimestamp(version.created_at) : "Unknown time",
      version.deleted ? "tombstone" : version.content_format,
    ];

    if (version.version === currentVersion) {
      parts.unshift("Current version");
    }

    return parts.join(" • ");
  }
</script>

{#if state.kind === "loading"}
  <p class="setting-item-description">Loading server history...</p>
{:else if state.kind === "error"}
  <p class="setting-item-description">Failed to load server history: {state.message}</p>
{:else if state.versions.length === 0}
  <p class="setting-item-description">No server history is available for this file yet.</p>
{:else}
  <div class="obsidian-sync-history-list">
    {#each state.versions as version (version.version)}
      <div class="setting-item">
        <div class="setting-item-info">
          <div class="setting-item-name">Version {version.version}</div>
          <div class="setting-item-description">{buildVersionDescription(version)}</div>
        </div>
        <div class="setting-item-control">
          {#if version.version === currentVersion}
            <button type="button" disabled>Current</button>
          {:else}
            <button
              type="button"
              disabled={restoringVersion === version.version}
              on:click={() => onRestore(version.version)}
            >
              {restoringVersion === version.version ? "Restoring..." : "Restore"}
            </button>
          {/if}
        </div>
      </div>
    {/each}
  </div>
{/if}

// plugin/src/ui/components/FileHistoryModal.vue
<script setup lang="ts">
import type { FileVersionItem } from "../../types";
import type { HistoryState } from "../file-history-types";

const props = defineProps<{
  currentVersion: number;
  state: HistoryState;
  restoringVersion: number | null;
  onRestore: (version: number) => void;
}>();

function formatTimestamp(value: string): string {
  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) {
    return value;
  }

  return parsed.toLocaleString();
}

function buildVersionDescription(version: FileVersionItem): string {
  const parts = [
    version.created_at ? formatTimestamp(version.created_at) : "Unknown time",
    version.deleted ? "tombstone" : version.content_format,
  ];

  if (version.version === props.currentVersion) {
    parts.unshift("Current version");
  }

  return parts.join(" • ");
}
</script>

<template>
  <p v-if="props.state.kind === 'loading'" class="setting-item-description">Loading server history...</p>
  <p v-else-if="props.state.kind === 'error'" class="setting-item-description">
    Failed to load server history: {{ props.state.message }}
  </p>
  <p v-else-if="props.state.versions.length === 0" class="setting-item-description">
    No server history is available for this file yet.
  </p>
  <div v-else class="obsidian-sync-history-list">
    <div v-for="version in props.state.versions" :key="version.version" class="setting-item">
      <div class="setting-item-info">
        <div class="setting-item-name">Version {{ version.version }}</div>
        <div class="setting-item-description">{{ buildVersionDescription(version) }}</div>
      </div>
      <div class="setting-item-control">
        <button v-if="version.version === props.currentVersion" type="button" disabled>Current</button>
        <button
          v-else
          type="button"
          :disabled="props.restoringVersion === version.version"
          @click="props.onRestore(version.version)"
        >
          {{ props.restoringVersion === version.version ? "Restoring..." : "Restore" }}
        </button>
      </div>
    </div>
  </div>
</template>
